/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package libraryproject;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.util.CellRangeAddress;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author admin
 */
public class Main extends javax.swing.JFrame {
    

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }
    private String studynum;


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ParentPanel = new javax.swing.JPanel();
        LoginPanel = new javax.swing.JPanel();
        titleLogin = new javax.swing.JLabel();
        label1Login = new javax.swing.JLabel();
        StudentLogin = new javax.swing.JLabel();
        StudNumTextFieldLogin = new javax.swing.JTextField();
        passLabelLogin = new javax.swing.JLabel();
        passFieldLogin = new javax.swing.JPasswordField();
        label2Login = new javax.swing.JLabel();
        hyperlinkSignUp_Login = new javax.swing.JButton();
        checkboxLogin = new javax.swing.JCheckBox();
        LoginButton = new javax.swing.JButton();
        SignUpPanel = new javax.swing.JPanel();
        titleSignUp = new javax.swing.JLabel();
        label1SignUp = new javax.swing.JLabel();
        StudentSignUp = new javax.swing.JLabel();
        StudentTextFieldSignUp = new javax.swing.JTextField();
        nameSignUp = new javax.swing.JLabel();
        nameTextFieldSignUp = new javax.swing.JTextField();
        passLabelSignUp = new javax.swing.JLabel();
        passFieldSignUp = new javax.swing.JPasswordField();
        label2SignUp = new javax.swing.JLabel();
        hyperlinkLogin_SignUp = new javax.swing.JButton();
        checkboxSignUp = new javax.swing.JCheckBox();
        SignUpButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        ParentPanel.setBackground(new java.awt.Color(255, 255, 255));
        ParentPanel.setPreferredSize(new java.awt.Dimension(620, 520));
        ParentPanel.setRequestFocusEnabled(false);
        ParentPanel.setLayout(new java.awt.CardLayout());

        LoginPanel.setBackground(new java.awt.Color(255, 255, 255));
        LoginPanel.setRequestFocusEnabled(false);
        LoginPanel.setVerifyInputWhenFocusTarget(false);

        titleLogin.setFont(new java.awt.Font("Cambria", 1, 48)); // NOI18N
        titleLogin.setForeground(new java.awt.Color(0, 102, 0));
        titleLogin.setText("SJC Library System");

        label1Login.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        label1Login.setForeground(new java.awt.Color(0, 102, 0));
        label1Login.setText("Login to your account");

        StudentLogin.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        StudentLogin.setForeground(new java.awt.Color(0, 51, 0));
        StudentLogin.setText("Student Number");

        StudNumTextFieldLogin.setToolTipText("");
        StudNumTextFieldLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudNumTextFieldLoginActionPerformed(evt);
            }
        });
        StudNumTextFieldLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                StudNumTextFieldLoginKeyPressed(evt);
            }
        });

        passLabelLogin.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        passLabelLogin.setForeground(new java.awt.Color(0, 51, 0));
        passLabelLogin.setText("Password ");

        passFieldLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passFieldLoginActionPerformed(evt);
            }
        });
        passFieldLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passFieldLoginKeyPressed(evt);
            }
        });

        label2Login.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        label2Login.setText("Already have an account?");

        hyperlinkSignUp_Login.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        hyperlinkSignUp_Login.setForeground(new java.awt.Color(51, 102, 0));
        hyperlinkSignUp_Login.setText("SIGN UP");
        hyperlinkSignUp_Login.setBorder(null);
        hyperlinkSignUp_Login.setContentAreaFilled(false);
        hyperlinkSignUp_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hyperlinkSignUp_LoginActionPerformed(evt);
            }
        });

        checkboxLogin.setText("Show Password?");
        checkboxLogin.setContentAreaFilled(false);
        checkboxLogin.setFocusable(false);
        checkboxLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxLoginActionPerformed(evt);
            }
        });

        LoginButton.setBackground(new java.awt.Color(0, 102, 0));
        LoginButton.setForeground(new java.awt.Color(255, 255, 255));
        LoginButton.setText("LOG IN");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginPanelLayout = new javax.swing.GroupLayout(LoginPanel);
        LoginPanel.setLayout(LoginPanelLayout);
        LoginPanelLayout.setHorizontalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(StudNumTextFieldLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                                .addComponent(StudentLogin)
                                .addComponent(LoginButton, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                                .addComponent(passLabelLogin)
                                .addComponent(passFieldLogin)
                                .addGroup(LoginPanelLayout.createSequentialGroup()
                                    .addComponent(label2Login)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(hyperlinkSignUp_Login)))
                            .addComponent(checkboxLogin)))
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(titleLogin))
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(label1Login)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        LoginPanelLayout.setVerticalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(titleLogin)
                .addGap(18, 18, 18)
                .addComponent(label1Login)
                .addGap(30, 30, 30)
                .addComponent(StudentLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StudNumTextFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passLabelLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkboxLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hyperlinkSignUp_Login)
                    .addComponent(label2Login))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        ParentPanel.add(LoginPanel, "card3");

        SignUpPanel.setBackground(new java.awt.Color(255, 255, 255));
        SignUpPanel.setPreferredSize(new java.awt.Dimension(620, 540));
        SignUpPanel.setRequestFocusEnabled(false);
        SignUpPanel.setVerifyInputWhenFocusTarget(false);

        titleSignUp.setFont(new java.awt.Font("Cambria", 1, 48)); // NOI18N
        titleSignUp.setForeground(new java.awt.Color(0, 102, 0));
        titleSignUp.setText("SJC Library System");

        label1SignUp.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        label1SignUp.setForeground(new java.awt.Color(0, 102, 0));
        label1SignUp.setText("Create an account");

        StudentSignUp.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        StudentSignUp.setForeground(new java.awt.Color(0, 51, 0));
        StudentSignUp.setText("Student Number");

        StudentTextFieldSignUp.setToolTipText("");
        StudentTextFieldSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentTextFieldSignUpActionPerformed(evt);
            }
        });
        StudentTextFieldSignUp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                StudentTextFieldSignUpKeyPressed(evt);
            }
        });

        nameSignUp.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        nameSignUp.setForeground(new java.awt.Color(0, 51, 0));
        nameSignUp.setText("Name");

        nameTextFieldSignUp.setToolTipText("");
        nameTextFieldSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldSignUpActionPerformed(evt);
            }
        });
        nameTextFieldSignUp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameTextFieldSignUpKeyPressed(evt);
            }
        });

        passLabelSignUp.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        passLabelSignUp.setForeground(new java.awt.Color(0, 51, 0));
        passLabelSignUp.setText("Password ");

        passFieldSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passFieldSignUpActionPerformed(evt);
            }
        });
        passFieldSignUp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passFieldSignUpKeyPressed(evt);
            }
        });

        label2SignUp.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        label2SignUp.setText("Already have an account?");

        hyperlinkLogin_SignUp.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        hyperlinkLogin_SignUp.setForeground(new java.awt.Color(51, 102, 0));
        hyperlinkLogin_SignUp.setText("LOG IN");
        hyperlinkLogin_SignUp.setBorder(null);
        hyperlinkLogin_SignUp.setContentAreaFilled(false);
        hyperlinkLogin_SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hyperlinkLogin_SignUpActionPerformed(evt);
            }
        });

        checkboxSignUp.setText("Show Password?");
        checkboxSignUp.setContentAreaFilled(false);
        checkboxSignUp.setFocusable(false);
        checkboxSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxSignUpActionPerformed(evt);
            }
        });

        SignUpButton.setBackground(new java.awt.Color(0, 102, 0));
        SignUpButton.setForeground(new java.awt.Color(255, 255, 255));
        SignUpButton.setText("SIGN UP");
        SignUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SignUpPanelLayout = new javax.swing.GroupLayout(SignUpPanel);
        SignUpPanel.setLayout(SignUpPanelLayout);
        SignUpPanelLayout.setHorizontalGroup(
            SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignUpPanelLayout.createSequentialGroup()
                .addGroup(SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SignUpPanelLayout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addGroup(SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SignUpPanelLayout.createSequentialGroup()
                                .addComponent(label2SignUp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hyperlinkLogin_SignUp))
                            .addComponent(StudentTextFieldSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StudentSignUp)
                            .addComponent(nameSignUp)
                            .addComponent(nameTextFieldSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passLabelSignUp)
                            .addComponent(passFieldSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkboxSignUp)
                            .addComponent(SignUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(SignUpPanelLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(titleSignUp))
                    .addGroup(SignUpPanelLayout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(label1SignUp)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        SignUpPanelLayout.setVerticalGroup(
            SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignUpPanelLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(titleSignUp)
                .addGap(18, 18, 18)
                .addComponent(label1SignUp)
                .addGap(30, 30, 30)
                .addComponent(StudentSignUp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StudentTextFieldSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameSignUp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameTextFieldSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passLabelSignUp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passFieldSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkboxSignUp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SignUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hyperlinkLogin_SignUp)
                    .addComponent(label2SignUp))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        ParentPanel.add(SignUpPanel, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ParentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ParentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SignUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpButtonActionPerformed

        String studentNum = StudentTextFieldSignUp.getText().trim();
        String name = nameTextFieldSignUp.getText().trim();
        String password = passFieldSignUp.getText().trim();
        

        boolean hasErrors = false;
        if (studentNum.isEmpty()) {
            hasErrors = true;
            StudentTextFieldSignUp.setBorder(BorderFactory.createLineBorder(Color.RED));
        }
        else {
            StudentTextFieldSignUp.setBorder(UIManager.getBorder("TextField.border"));
        }
        ////
        if (name.isEmpty()) {
            hasErrors = true;
            nameTextFieldSignUp.setBorder(BorderFactory.createLineBorder(Color.RED));
        }
        else {
            nameTextFieldSignUp.setBorder(UIManager.getBorder("TextField.border"));
        }
        ////
        if (password.isEmpty()) {
            hasErrors = true;
            passFieldSignUp.setBorder(BorderFactory.createLineBorder(Color.RED));
        }
        else {
            passFieldSignUp.setBorder(UIManager.getBorder("TextField.border"));
        }
        ////

        if (hasErrors) {
            JOptionPane.showMessageDialog(null, "The form you submitted is incomplete.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                InputStream file = getClass().getClassLoader().getResourceAsStream("BookInfo.xlsx");
                XSSFWorkbook workbook = new XSSFWorkbook(file);
                XSSFSheet sheet = workbook.getSheetAt(2);
                int lastRowNum = sheet.getLastRowNum();
                int lastID = 0;
                
                if (lastRowNum >= 1) {
                    XSSFCell lastIDCell = sheet.getRow(lastRowNum).getCell(0);
                    if (lastIDCell != null) {
                        lastID = (int) lastIDCell.getNumericCellValue();
                    }
                }
                
                Row row = sheet.createRow(lastRowNum + 1);
                int ID = lastID + 1;
                row.createCell(0).setCellValue(ID);
                
                row.createCell(1).setCellValue(studentNum);
                CellRangeAddress mergedStudentNum = new CellRangeAddress(lastRowNum + 1, lastRowNum + 1, 1, 2);
                sheet.addMergedRegion(mergedStudentNum);
                
                row.createCell(3).setCellValue(name);
                CellRangeAddress mergedName = new CellRangeAddress(lastRowNum + 1, lastRowNum + 1, 3, 4);
                sheet.addMergedRegion(mergedName);
                
                row.createCell(5).setCellValue(password);
                CellRangeAddress mergedPass = new CellRangeAddress(lastRowNum + 1, lastRowNum + 1, 5, 6);
                sheet.addMergedRegion(mergedPass);
                
                lastID = ID;
                file.close();
                
                FileOutputStream outFile = new FileOutputStream(new File(getClass().getClassLoader().getResource("BookInfo.xlsx").getFile()));
                workbook.write(outFile);
                outFile.close();
                
                System.out.println("Student Number: " + studentNum);
                System.out.println("Name: " + name);
                System.out.println("Password: " + password);
                JOptionPane.showMessageDialog(null, "Sign-up complete!", "Success", JOptionPane.INFORMATION_MESSAGE);
                
                //switch to login
                ParentPanel.removeAll();
                ParentPanel.add(LoginPanel);
                ParentPanel.repaint();
                ParentPanel.revalidate();
            }
            catch (IOException ex) {
                System.out.println("Error: " + ex.getMessage());
        }    
} 
    }//GEN-LAST:event_SignUpButtonActionPerformed

    private void checkboxSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxSignUpActionPerformed
        if (checkboxSignUp.isSelected()) {
            passFieldSignUp.setEchoChar((char) 0);
        } else {
            passFieldSignUp.setEchoChar('*');
        }
    }//GEN-LAST:event_checkboxSignUpActionPerformed

    private void hyperlinkLogin_SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hyperlinkLogin_SignUpActionPerformed
        ParentPanel.removeAll();
        ParentPanel.add(LoginPanel);
        ParentPanel.repaint();
        ParentPanel.revalidate();
    }//GEN-LAST:event_hyperlinkLogin_SignUpActionPerformed

    private void passFieldSignUpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passFieldSignUpKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            SignUpButton.doClick();
        }
    }//GEN-LAST:event_passFieldSignUpKeyPressed

    private void passFieldSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passFieldSignUpActionPerformed

    }//GEN-LAST:event_passFieldSignUpActionPerformed

    private void nameTextFieldSignUpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTextFieldSignUpKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            passFieldSignUp.requestFocus();
        }
    }//GEN-LAST:event_nameTextFieldSignUpKeyPressed

    private void nameTextFieldSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldSignUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldSignUpActionPerformed

    private void StudentTextFieldSignUpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_StudentTextFieldSignUpKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            nameTextFieldSignUp.requestFocus();
        }
    }//GEN-LAST:event_StudentTextFieldSignUpKeyPressed

    private void StudentTextFieldSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentTextFieldSignUpActionPerformed

    }//GEN-LAST:event_StudentTextFieldSignUpActionPerformed

    private void StudNumTextFieldLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudNumTextFieldLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StudNumTextFieldLoginActionPerformed

    private void StudNumTextFieldLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_StudNumTextFieldLoginKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            passFieldLogin.requestFocus();
        }
    }//GEN-LAST:event_StudNumTextFieldLoginKeyPressed

    private void passFieldLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passFieldLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passFieldLoginActionPerformed

    private void passFieldLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passFieldLoginKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            LoginButton.doClick();
        }
    }//GEN-LAST:event_passFieldLoginKeyPressed

    private void checkboxLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxLoginActionPerformed
    if (checkboxLogin.isSelected()) {
            passFieldLogin.setEchoChar((char) 0);
        } else {
            passFieldLogin.setEchoChar('*');
        }
    }//GEN-LAST:event_checkboxLoginActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
    
        Home homeFrame = new Home();
        homeFrame.setTitle("SJC LIBRARY SYSTEM");
        homeFrame.setSize(1200, 700);
        homeFrame.setLocationRelativeTo(null);
        homeFrame.setResizable(false); 
        homeFrame.setDefaultCloseOperation(EXIT_ON_CLOSE);
        homeFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void hyperlinkSignUp_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hyperlinkSignUp_LoginActionPerformed
        ParentPanel.removeAll();
        ParentPanel.add(SignUpPanel);
        ParentPanel.repaint();
        ParentPanel.revalidate();
    }//GEN-LAST:event_hyperlinkSignUp_LoginActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
        } 
        
        catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            ex.printStackTrace();
    }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                Main mainFrame = new Main();
                mainFrame.setTitle("SJC LIBRARY SYSTEM");
                mainFrame.setSize(620, 540);
                mainFrame.setLocationRelativeTo(null);
                mainFrame.setResizable(false); 
                mainFrame.setDefaultCloseOperation(EXIT_ON_CLOSE);
                mainFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginButton;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JPanel ParentPanel;
    private javax.swing.JButton SignUpButton;
    private javax.swing.JPanel SignUpPanel;
    private javax.swing.JTextField StudNumTextFieldLogin;
    private javax.swing.JLabel StudentLogin;
    private javax.swing.JLabel StudentSignUp;
    private javax.swing.JTextField StudentTextFieldSignUp;
    private javax.swing.JCheckBox checkboxLogin;
    private javax.swing.JCheckBox checkboxSignUp;
    private javax.swing.JButton hyperlinkLogin_SignUp;
    private javax.swing.JButton hyperlinkSignUp_Login;
    private javax.swing.JLabel label1Login;
    private javax.swing.JLabel label1SignUp;
    private javax.swing.JLabel label2Login;
    private javax.swing.JLabel label2SignUp;
    private javax.swing.JLabel nameSignUp;
    private javax.swing.JTextField nameTextFieldSignUp;
    private javax.swing.JPasswordField passFieldLogin;
    private javax.swing.JPasswordField passFieldSignUp;
    private javax.swing.JLabel passLabelLogin;
    private javax.swing.JLabel passLabelSignUp;
    private javax.swing.JLabel titleLogin;
    private javax.swing.JLabel titleSignUp;
    // End of variables declaration//GEN-END:variables
}
